In [1]:
print("Hello")

Hello

In [2]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
bank_marketing = fetch_ucirepo(id=222)

# data (as pandas dataframes)
X = bank_marketing.data.features
y = bank_marketing.data.targets

# metadata
print(bank_marketing.metadata)

# variable information
print(bank_marketing.variables)

{'uci_id': 222, 'name': 'Bank Marketing', 'repository_url': 'https://archive.ics.uci.edu/dataset/222/bank+marketing', 'data_url': 'https://archive.ics.uci.edu/static/public/222/data.csv', 'abstract': 'The data is related with direct marketing campaigns (phone calls) of a Portuguese banking institution. The classification goal is to predict if the client will subscribe a term deposit (variable y).', 'area': 'Business', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 45211, 'num_features': 16, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Age', 'Occupation', 'Marital Status', 'Education Level'], 'target_col': ['y'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 2014, 'last_updated': 'Fri Aug 18 2023', 'dataset_doi': '10.24432/C5K306', 'creators': ['S. Moro', 'P. Rita', 'P. Cortez'], 'intro_paper': {'ID': 277, 'type': 'NATIVE', 'title': 'A data-driven approach to predict the success of bank telemarketing', 'authors': 'Sérgio Moro, P. Cortez, P. Rita', 'venue': 'Decision Support Systems', 'year': 2014, 'journal': None, 'DOI': '10.1016/j.dss.2014.03.001', 'URL': 'https://www.semanticscholar.org/paper/cab86052882d126d43f72108c6cb41b295cc8a9e', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': "The data is related with direct marketing campaigns of a Portuguese banking institution. The marketing campaigns were based on phone calls. Often, more than one contact to the same client was required, in order to access if the product (bank term deposit) would be ('yes') or not ('no') subscribed. \n\nThere are four datasets: \n1) bank-additional-full.csv with all examples (41188) and 20 inputs, ordered by date (from May 2008 to November 2010), very close to the data analyzed in [Moro et al., 2014]\n2) bank-additional.csv with 10% of the examples (4119), randomly selected from 1), and 20 inputs.\n3) bank-full.csv with all examples and 17 inputs, ordered by date (older version of this dataset with less inputs). \n4) bank.csv with 10% of the examples and 17 inputs, randomly selected from 3 (older version of this dataset with less inputs). \nThe smallest datasets are provided to test more computationally demanding machine learning algorithms (e.g., SVM). \n\nThe classification goal is to predict if the client will subscribe (yes/no) a term deposit (variable y).", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Input variables:\n   # bank client data:\n   1 - age (numeric)\n   2 - job : type of job (categorical: "admin.","unknown","unemployed","management","housemaid","entrepreneur","student",\n                                       "blue-collar","self-employed","retired","technician","services") \n   3 - marital : marital status (categorical: "married","divorced","single"; note: "divorced" means divorced or widowed)\n   4 - education (categorical: "unknown","secondary","primary","tertiary")\n   5 - default: has credit in default? (binary: "yes","no")\n   6 - balance: average yearly balance, in euros (numeric) \n   7 - housing: has housing loan? (binary: "yes","no")\n   8 - loan: has personal loan? (binary: "yes","no")\n   # related with the last contact of the current campaign:\n   9 - contact: contact communication type (categorical: "unknown","telephone","cellular") \n  10 - day: last contact day of the month (numeric)\n  11 - month: last contact month of year (categorical: "jan", "feb", "mar", ..., "nov", "dec")\n  12 - duration: last contact duration, in seconds (numeric)\n   # other attributes:\n  13 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)\n  14 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric, -1 means client was not previously contacted)\n  15 - previous: number of contacts performed before this campaign and for this client (numeric)\n  16 - poutcome: outcome of the previous marketing campaign (categorical: "unknown","other","failure","success")\n\n  Output variable (desired target):\n  17 - y - has the client subscribed a term deposit? (binary: "yes","no")\n', 'citation': None}}
           name     role         type      demographic  \
0           age  Feature      Integer              Age
1           job  Feature  Categorical       Occupation
2       marital  Feature  Categorical   Marital Status
3     education  Feature  Categorical  Education Level
4       default  Feature       Binary             None
5       balance  Feature      Integer             None
6       housing  Feature       Binary             None
7          loan  Feature       Binary             None
8       contact  Feature  Categorical             None
9   day_of_week  Feature         Date             None
10        month  Feature         Date             None
11     duration  Feature      Integer             None
12     campaign  Feature      Integer             None
13        pdays  Feature      Integer             None
14     previous  Feature      Integer             None
15     poutcome  Feature  Categorical             None
16            y   Target       Binary             None

                                          description  units missing_values
0                                                None   None             no
1   type of job (categorical: 'admin.','blue-colla...   None             no
2   marital status (categorical: 'divorced','marri...   None             no
3   (categorical: 'basic.4y','basic.6y','basic.9y'...   None             no
4                              has credit in default?   None             no
5                              average yearly balance  euros             no
6                                   has housing loan?   None             no
7                                  has personal loan?   None             no
8   contact communication type (categorical: 'cell...   None            yes
9                        last contact day of the week   None             no
10  last contact month of year (categorical: 'jan'...   None             no
11   last contact duration, in seconds (numeric). ...   None             no
12  number of contacts performed during this campa...   None             no
13  number of days that passed by after the client...   None            yes
14  number of contacts performed before this campa...   None             no
15  outcome of the previous marketing campaign (ca...   None            yes
16          has the client subscribed a term deposit?   None             no

In [3]:
import pandas as pd
data_df = pd.concat((X,y),axis=1)

In [4]:
data_df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day_of_week,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,NaN,5,may,261,1,-1,0,NaN,no
1,44,technician,single,secondary,no,29,yes,no,NaN,5,may,151,1,-1,0,NaN,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,NaN,5,may,76,1,-1,0,NaN,no
3,47,blue-collar,married,NaN,no,1506,yes,no,NaN,5,may,92,1,-1,0,NaN,no
4,33,NaN,single,NaN,no,1,no,no,NaN,5,may,198,1,-1,0,NaN,no

In [5]:
data_df.shape

(45211, 17)

In [6]:
object_col = data_df.select_dtypes(include='object')
object_col

,job,marital,education,default,housing,loan,contact,month,poutcome,y
0,management,married,tertiary,no,yes,no,NaN,may,NaN,no
1,technician,single,secondary,no,yes,no,NaN,may,NaN,no
2,entrepreneur,married,secondary,no,yes,yes,NaN,may,NaN,no
3,blue-collar,married,NaN,no,yes,no,NaN,may,NaN,no
4,NaN,single,NaN,no,no,no,NaN,may,NaN,no
...,...,...,...,...,...,...,...,...,...,...
45206,technician,married,tertiary,no,no,no,cellular,nov,NaN,yes
45207,retired,divorced,primary,no,no,no,cellular,nov,NaN,yes
45208,retired,married,secondary,no,no,no,cellular,nov,success,yes
45209,blue-collar,married,secondary,no,no,no,telephone,nov,NaN,no
45210,entrepreneur,married,secondary,no,no,no,cellular,nov,other,no

In [7]:
import seaborn as sns
for i in object_col:
    print(data_df[i].value_counts())

job
blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
Name: count, dtype: int64
marital
married     27214
single      12790
divorced     5207
Name: count, dtype: int64
education
secondary    23202
tertiary     13301
primary       6851
Name: count, dtype: int64
default
no     44396
yes      815
Name: count, dtype: int64
housing
yes    25130
no     20081
Name: count, dtype: int64
loan
no     37967
yes     7244
Name: count, dtype: int64
contact
cellular     29285
telephone     2906
Name: count, dtype: int64
month
may    13766
jul     6895
aug     6247
jun     5341
nov     3970
apr     2932
feb     2649
jan     1403
oct      738
sep      579
mar      477
dec      214
Name: count, dtype: int64
poutcome
failure    4901
other      1840
success    1511
Name: count, dtype: int64
y
no     39922
yes     5289
Name: count, dtype: int64

In [8]:
data_df.isnull().sum()

age                0
job              288
marital            0
education       1857
default            0
balance            0
housing            0
loan               0
contact        13020
day_of_week        0
month              0
duration           0
campaign           0
pdays              0
previous           0
poutcome       36959
y                  0
dtype: int64

In [9]:
data_df.drop(columns=['contact','poutcome'],axis = 1,inplace = True)

In [10]:
data_df.isnull().sum()

age               0
job             288
marital           0
education      1857
default           0
balance           0
housing           0
loan              0
day_of_week       0
month             0
duration          0
campaign          0
pdays             0
previous          0
y                 0
dtype: int64

In [11]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   age          45211 non-null  int64
 1   job          44923 non-null  object
 2   marital      45211 non-null  object
 3   education    43354 non-null  object
 4   default      45211 non-null  object
 5   balance      45211 non-null  int64
 6   housing      45211 non-null  object
 7   loan         45211 non-null  object
 8   day_of_week  45211 non-null  int64
 9   month        45211 non-null  object
 10  duration     45211 non-null  int64
 11  campaign     45211 non-null  int64
 12  pdays        45211 non-null  int64
 13  previous     45211 non-null  int64
 14  y            45211 non-null  object
dtypes: int64(7), object(8)
memory usage: 5.2+ MB

In [12]:
data_df['job'].fillna(data_df['job'].mode()[0],inplace = True)
data_df['education'].fillna(data_df['education'].mode()[0],inplace = True)

In [13]:
data_df.isnull().sum()

age            0
job            0
marital        0
education      0
default        0
balance        0
housing        0
loan           0
day_of_week    0
month          0
duration       0
campaign       0
pdays          0
previous       0
y              0
dtype: int64

In [14]:
object_col

,job,marital,education,default,housing,loan,contact,month,poutcome,y
0,management,married,tertiary,no,yes,no,NaN,may,NaN,no
1,technician,single,secondary,no,yes,no,NaN,may,NaN,no
2,entrepreneur,married,secondary,no,yes,yes,NaN,may,NaN,no
3,blue-collar,married,NaN,no,yes,no,NaN,may,NaN,no
4,NaN,single,NaN,no,no,no,NaN,may,NaN,no
...,...,...,...,...,...,...,...,...,...,...
45206,technician,married,tertiary,no,no,no,cellular,nov,NaN,yes
45207,retired,divorced,primary,no,no,no,cellular,nov,NaN,yes
45208,retired,married,secondary,no,no,no,cellular,nov,success,yes
45209,blue-collar,married,secondary,no,no,no,telephone,nov,NaN,no
45210,entrepreneur,married,secondary,no,no,no,cellular,nov,other,no

In [15]:
object_col = data_df.select_dtypes(include='object')

In [16]:
import joblib
from sklearn.preprocessing import LabelEncoder
encoder = {}
for i in object_col:
    lab_enc = LabelEncoder()
    data_df[i] = lab_enc.fit_transform(data_df[i])
    encoder[i] = lab_enc

In [17]:
print(encoder)

{'job': LabelEncoder(), 'marital': LabelEncoder(), 'education': LabelEncoder(), 'default': LabelEncoder(), 'housing': LabelEncoder(), 'loan': LabelEncoder(), 'month': LabelEncoder(), 'y': LabelEncoder()}

In [18]:
joblib.dump(encoder,"encoder.pkl")

['encoder.pkl']

In [19]:
data_df.head()

,age,job,marital,education,default,balance,housing,loan,day_of_week,month,duration,campaign,pdays,previous,y
0,58,4,1,2,0,2143,1,0,5,8,261,1,-1,0,0
1,44,9,2,1,0,29,1,0,5,8,151,1,-1,0,0
2,33,2,1,1,0,2,1,1,5,8,76,1,-1,0,0
3,47,1,1,1,0,1506,1,0,5,8,92,1,-1,0,0
4,33,1,2,1,0,1,0,0,5,8,198,1,-1,0,0

In [20]:
from sklearn.preprocessing import MinMaxScaler
min_max_scale = MinMaxScaler()
normalize_col = ['age','balance','duration']

data_df[normalize_col] = min_max_scale.fit_transform(data_df[normalize_col])

In [21]:
print("Hello")

Hello

In [22]:
data_df

,age,job,marital,education,default,balance,housing,loan,day_of_week,month,duration,campaign,pdays,previous,y
0,0.519481,4,1,2,0,0.092259,1,0,5,8,0.053070,1,-1,0,0
1,0.337662,9,2,1,0,0.073067,1,0,5,8,0.030704,1,-1,0,0
2,0.194805,2,1,1,0,0.072822,1,1,5,8,0.015453,1,-1,0,0
3,0.376623,1,1,1,0,0.086476,1,0,5,8,0.018707,1,-1,0,0
4,0.194805,1,2,1,0,0.072812,0,0,5,8,0.040260,1,-1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,0.428571,9,1,2,0,0.080293,0,0,17,9,0.198658,3,-1,0,1
45207,0.688312,5,0,0,0,0.088501,0,0,17,9,0.092721,2,-1,0,1
45208,0.701299,5,1,1,0,0.124689,0,0,17,9,0.229158,5,184,3,1
45209,0.506494,1,1,1,0,0.078868,0,0,17,9,0.103294,4,-1,0,0
45210,0.246753,2,1,1,0,0.099777,0,0,17,9,0.073404,2,188,11,0

In [23]:
X = data_df.iloc[:,:-1]
y = data_df.iloc[:,-1]

In [24]:
X

,age,job,marital,education,default,balance,housing,loan,day_of_week,month,duration,campaign,pdays,previous
0,0.519481,4,1,2,0,0.092259,1,0,5,8,0.053070,1,-1,0
1,0.337662,9,2,1,0,0.073067,1,0,5,8,0.030704,1,-1,0
2,0.194805,2,1,1,0,0.072822,1,1,5,8,0.015453,1,-1,0
3,0.376623,1,1,1,0,0.086476,1,0,5,8,0.018707,1,-1,0
4,0.194805,1,2,1,0,0.072812,0,0,5,8,0.040260,1,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,0.428571,9,1,2,0,0.080293,0,0,17,9,0.198658,3,-1,0
45207,0.688312,5,0,0,0,0.088501,0,0,17,9,0.092721,2,-1,0
45208,0.701299,5,1,1,0,0.124689,0,0,17,9,0.229158,5,184,3
45209,0.506494,1,1,1,0,0.078868,0,0,17,9,0.103294,4,-1,0
45210,0.246753,2,1,1,0,0.099777,0,0,17,9,0.073404,2,188,11

In [25]:
y

0        0
1        0
2        0
3        0
4        0
        ..
45206    1
45207    1
45208    1
45209    0
45210    0
Name: y, Length: 45211, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split, KFold,cross_val_score
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20)

In [27]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

In [28]:
paragird = {'n_estimators':[100,150,200],
            'max_features':[10,20,30],
            'max_depth':[5,10,40],
            'min_samples_leaf':[2,3,4],
            "criterion":['gini','entropy','log_loss']}

In [29]:
rf_model = RandomForestClassifier()

In [30]:
grid_model = GridSearchCV(estimator=rf_model,
                    param_grid=paragird,
                    cv=5)

In [ ]:
grid_model.fit(X_train,y_train)

In [ ]:
grid_model.best_params_